### ISSUE TITLE
Ability to reference unsupported objects

### ISSUE THREAD

**Issue by zuaresc** [errordeveloper/kubegen#20]
I would like to be able to use `kubegen` with OpenShift objects (DeploymentConfigs, Routes, ImageStreams, etc). The ability to reference any arbitrary resources, even in full-form would be a nice feature. Additionally, with `CustomResourceDefinitions` stabilizing, I feel that this may become a more common use-case.

If this is already possible and I'm missing something, please let me know.

**Comment by errordeveloper** [comment]
@zuaresc thanks for your interest in kubegen! I don't think this is supported right now, but I've thought of this and see it as a feature we should add.

**Comment by errordeveloper** [comment]
Adding macros to any object would be fairly easy, by the way.
Another use-case for this is migration – you should be able to just put any files you already have into a module. The bit I'm not sure about is whether you should be able to just put such files in a module directory, or explicit referencing is a reasonable amount of effort to ask for...

**Comment by errordeveloper** [comment]
For now, I opted for implicit inclusion, as it would allow conditional inclusion (well, we don't have branching macros, but for now `kubegen.String.Lookup` can be used to determine file path based on a parameter, or even `kubegen.Array.Lookup` for a whole set of resources to include). Examples are coming soon, will need to revamp the docs and example in general.
