### ISSUE TITLE
inheritance

### ISSUE THREAD

**Issue by errordeveloper** [errordeveloper/kubegen#8]
We have modules which provide high level re-usesability. Some basic inheritance with simple merge rules would be nice. It is perhaps reasonable to consider inheritance within module vs nested module, both of which are fairly simple models.

**Comment by errordeveloper** [comment]
In terms of examples, Sock Shop has 3 instances of MongoDB where only `image` different:
- [`orders-db`](https://github.com/errordeveloper/kubegen/blob/d9422f424c7da138ef4cda85fd44485b5b3a633d/examples/modules/sockshop/orders.yml#L38)
- [`user-db`](https://github.com/errordeveloper/kubegen/blob/d9422f424c7da138ef4cda85fd44485b5b3a633d/examples/modules/sockshop/user.yml#L34)
- [`cart-db`](https://github.com/errordeveloper/kubegen/blob/d9422f424c7da138ef4cda85fd44485b5b3a633d/examples/modules/sockshop/cart.yml#L38)

**Comment by errordeveloper** [comment]
We could consider having `fromPartial: path` in each struct, but we should only allow one level of inheritance this way.

**Comment by errordeveloper** [comment]
As I mentioned, this relates to #6 and the above could be re-considered as `{{ include partialPath }}`.
If we go with `fromPartial: path`, which I tend to prefer, it makes more sense having templates that adhere to JSON/YAML/HCL syntax.

**Comment by wallrj** [comment]
Hey @errordeveloper Nice chatting to you this afternoon :-)
https://github.com/geofffranks/spruce is the project I was thinking of which (I think) allows you to merge yaml files and add macros to yaml files, filled from other yaml files. Might be re-usable?

**Comment by errordeveloper** [comment]
Thanks, Richard!

**Comment by errordeveloper** [comment]
We have basic machinery with `kubegen.Object.Lookup` now in master, but we still need to allow merging objects. Merging arrays will be possible once we have `kubegen.Array.Lookup` (which should be trivial).

**Comment by errordeveloper** [comment]
Closed via #21.
